# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rexml/all/rexml.rbi
#
# rexml-3.2.5

module REXML
end
class REXML::Document < REXML::Element
  def <<(child); end
  def add(child); end
  def add_element(arg = nil, arg2 = nil); end
  def build(source); end
  def clone; end
  def doctype; end
  def document; end
  def encoding; end
  def entity_expansion_count; end
  def expanded_name; end
  def initialize(source = nil, context = nil); end
  def name; end
  def node_type; end
  def record_entity_expansion; end
  def root; end
  def self.entity_expansion_limit; end
  def self.entity_expansion_limit=(val); end
  def self.entity_expansion_text_limit; end
  def self.entity_expansion_text_limit=(val); end
  def self.parse_stream(source, listener); end
  def stand_alone?; end
  def version; end
  def write(*arguments); end
  def xml_decl; end
end
