# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/webrick/all/webrick.rbi
#
# webrick-1.7.0

module WEBrick
end
class WEBrick::Cookie
  def comment; end
  def comment=(arg0); end
  def domain; end
  def domain=(arg0); end
  def expires; end
  def expires=(t); end
  def initialize(name, value); end
  def max_age; end
  def max_age=(arg0); end
  def name; end
  def path; end
  def path=(arg0); end
  def secure; end
  def secure=(arg0); end
  def self.parse(str); end
  def self.parse_set_cookie(str); end
  def self.parse_set_cookies(str); end
  def to_s; end
  def value; end
  def value=(arg0); end
  def version; end
  def version=(arg0); end
end
