# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/diff-lcs/all/diff-lcs.rbi
#
# diff-lcs-1.5.0

module Diff
end
module Diff::LCS
  def diff(other, callbacks = nil, &block); end
  def lcs(other, &block); end
  def patch!(patchset); end
  def patch(patchset); end
  def patch_me(patchset); end
  def sdiff(other, callbacks = nil, &block); end
  def self.LCS(seq1, seq2, &block); end
  def self.diff(seq1, seq2, callbacks = nil, &block); end
  def self.lcs(seq1, seq2, &block); end
  def self.patch!(src, patchset); end
  def self.patch(src, patchset, direction = nil); end
  def self.sdiff(seq1, seq2, callbacks = nil, &block); end
  def self.traverse_balanced(seq1, seq2, callbacks = nil); end
  def self.traverse_sequences(seq1, seq2, callbacks = nil); end
  def self.unpatch!(src, patchset); end
  def traverse_balanced(other, callbacks = nil, &block); end
  def traverse_sequences(other, callbacks = nil, &block); end
  def unpatch!(patchset); end
  def unpatch(patchset); end
  def unpatch_me(patchset); end
end
