# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/reverse_markdown/all/reverse_markdown.rbi
#
# reverse_markdown-2.1.1

module ReverseMarkdown
  def self.cleaner; end
  def self.config; end
  def self.convert(input, options = nil); end
end
