# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/syntax_tree/all/syntax_tree.rbi
#
# syntax_tree-2.7.1

module SyntaxTree
  def self.format(source, maxwidth = nil); end
  def self.parse(source); end
  def self.read(filepath); end
  def self.register_handler(extension, handler); end
end
