# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tilt/all/tilt.rbi
#
# tilt-2.0.10

module Tilt
  def self.[](file); end
  def self.current_template; end
  def self.default_mapping; end
  def self.lazy_map; end
  def self.new(file, line = nil, options = nil, &block); end
  def self.prefer(template_class, *extensions); end
  def self.register(template_class, *extensions); end
  def self.register_lazy(class_name, file, *extensions); end
  def self.registered?(ext); end
  def self.template_for(file); end
  def self.templates_for(file); end
end
class Tilt::Cache
  def clear; end
  def fetch(*key); end
  def initialize; end
end
